### ISSUE TITLE
systemic unresponsiveness in aggrwalk

### ISSUE THREAD

**Issue by Licenser** [bcantrill/node-libdtrace#5]
I every now and then get the following message:

```
couldn't get status: Abort due to systemic unresponsiveness 
 Error: couldn't get status: Abort due to systemic unresponsiveness
    at /opt/vmwebadm/js/server.js:8607:5
    at /opt/vmwebadm/js/server.js:8906:20
    at /opt/vmwebadm/js/server.js:9676:86
    at /opt/vmwebadm/js/server.js:8538:107
    at /opt/vmwebadm/js/server.js:9675:68
    at Server.<anonymous> (/opt/vmwebadm/js/server.js:9867:33)
    at Server.emit (events.js:70:17)
    at HTTPParser.onIncoming (http.js:1514:12)
    at HTTPParser.onHeadersComplete (http.js:102:31)
    at Socket.ondata (http.js:1410:22)
```

It seems to occur before entering the handler function for aggrwalk (got debug output before the call of aggrwalk but not in the first call of the function. Any ideas?

**Comment by Licenser** [comment]
rmustacc helped solve this one - problem was that I did not query the consumer often enough so it went into a dead state :). Just as an idea, this could be mentioned in the readme?

Regards!
